### ISSUE TITLE
Operations execute concurrently despite thread_count=1

### ISSUE THREAD

**Issue by jdellithorpe** [ldbc/ldbc_snb_driver#62]
Even though the configuration parameter thread_count is set to 1, when running the SNB interactive workload operations, operations appear to be executing concurrently anyway. See output below, which states that `2 handlers were mid-execution`. The `IndexOutOfBoundsException` appears to be a result of unexpected concurrent access in the DbConnectionState object shared between operation handlers.

```
Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Error running workload
        at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:405)
        at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:138)
        at com.ldbc.driver.Client.main(Client.java:53)
Caused by: com.ldbc.driver.ClientException: Error running workload

- Start Error Log -
        SOURCE: OperationHandlerRunnableContext [171] (Thread: ID=47, Name=OperationStreamExecutorServiceThread-1462827606264, Priority=5)
        ERROR:  Error encountered
LdbcUpdate7AddComment{commentId=274878603106, creationDate=Mon Oct 22 01:30:57 PDT 2012, locationIp='118.67.198.131', browserUsed='Firefox', content='right', length=5, authorPersonId=10995116285514, countryId=2
9, replyToPostId=-1, replyToCommentId=274878603101, tagIds=[]}
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jTransactionDriver.makeTxReqPayload(Neo4jTransactionDriver.java:775)
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jTransactionDriver.execAndCommit(Neo4jTransactionDriver.java:386)
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb$LdbcUpdate7AddCommentHandler.executeOperation(Neo4jDb.java:2012)
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb$LdbcUpdate7AddCommentHandler.executeOperation(Neo4jDb.java:1955)
        at com.ldbc.driver.OperationHandlerRunnableContext.run(OperationHandlerRunnableContext.java:147)
        at com.ldbc.driver.runtime.executor.SameThreadOperationExecutor.execute(SameThreadOperationExecutor.java:59)
        at com.ldbc.driver.runtime.executor.OperationStreamExecutorServiceThread.run(OperationStreamExecutorServiceThread.java:48)

        SOURCE: OperationHandlerRunnableContext [171] (Thread: ID=48, Name=ThreadPoolOperationExecutor-id(1462827606263)-thread(0), Priority=5)
        ERROR:  Error encountered
LdbcShortQuery4MessageContent{messageId=257704601407}
java.lang.NullPointerException
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb$LdbcShortQuery4MessageContentHandler.executeOperation(Neo4jDb.java:1412)
        at net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb$LdbcShortQuery4MessageContentHandler.executeOperation(Neo4jDb.java:1384)
        at com.ldbc.driver.OperationHandlerRunnableContext.run(OperationHandlerRunnableContext.java:147)
        at com.ldbc.driver.runtime.executor.ChildOperationExecutor.execute(ChildOperationExecutor.java:41)
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor$ThreadPoolExecutorWithAfterExecute.afterExecute(ThreadPoolOperationExecutor.java:211)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        SOURCE: WorkloadRunnerThread [514] (Thread: ID=43, Name=Thread-2, Priority=5)
        ERROR:  Encountered error while waiting for asynchronous executor to shutdown
Handlers still running: 1002
com.ldbc.driver.runtime.executor.OperationExecutorException: Error encountered while trying to shutdown
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:133)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.shutdownEverything(WorkloadRunner.java:510)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.run(WorkloadRunner.java:419)
Caused by: com.ldbc.driver.runtime.executor.OperationExecutorException: ThreadPoolOperationExecutor shutdown before all handlers could complete
1000 handlers were queued for execution but not yet started
2 handlers were mid-execution
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:127)
        ... 2 more

        SOURCE: OperationStreamExecutorServiceThread [53] (Thread: ID=45, Name=OperationStreamExecutorServiceThread-1462827606263, Priority=5)
```

**Comment by szarnyasg** [comment]
Using two write threads is expected, see Jack's comment at https://github.com/ldbc/ldbc_snb_driver/issues/119#issuecomment-612696965. So for the current version of the driver, I'd say implementations should be prepared for this.
